using go-healthcheck

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -41,10 +41,11 @@ FROM alpine:latest as stage1
 
 RUN apk add -U --no-cache ca-certificates
 
+# Install bash and curl, but we will remove curl later due to security concerns
 RUN apk add bash curl \
   && curl -fSsL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o /wait-for-it.sh \
-  && chmod +x /wait-for-it.sh  
-# && apk del curl
+  && chmod +x /wait-for-it.sh \
+  && apk del curl
 
 
 FROM stage1
@@ -68,8 +69,13 @@ ENV ENABLE_GRPC_SERVER_REFLECTION="true"
 ENV JWT_VALIDATORS__ISSUERS="@@@REPLACE@@@"
 ENV JWT_VALIDATORS__JWKS_URLS="@@@REPLACE@@@"
           
-HEALTHCHECK --interval=10s --timeout=3s \
-    CMD curl --fail -s http://localhost:50052/healthz | grep -q '{\"status\":\"SERVING\"}' || exit 1
+# DO NOT USE CURL. imagine if someone got access to your running docker container.
+#HEALTHCHECK --interval=10s --timeout=3s \
+#    CMD curl --fail -s http://localhost:50052/healthz | grep -q '{\"status\":\"SERVING\"}' || exit 1
+COPY --from=gregthebunny/go-healthcheck /bin/healthcheck /bin/healthcheck
+ENV PROBE='{{ .Assert.HTTPBodyContains .HTTP.Handler "GET" "http://localhost:50052/healthz" nil "SERVING" }}'
+HEALTHCHECK --start-period=10s --retries=3 --timeout=10s --interval=10s \
+    CMD ["/bin/healthcheck", "probe", "$PROBE"]
 
 # If necessary, CMD can be used to overwrite the mode in docker-compose to be "--gtm.mode=server" or "--gtm.mode=worker" 
 ENTRYPOINT ["/app/server"]
